# Generated by Django 5.0.4 on 2024-04-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.CharField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coffeehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coffeehouse')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('measure_unit', models.CharField(choices=[('ML', 'мл'), ('L', 'л'), ('GR', 'гр'), ('KG', 'кг')])),
                ('photo', models.ImageField(null=True, upload_to='menu_item_photo/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
    ]
