# Generated by Django 5.0.4 on 2024-04-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coffeehouse_slug_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='units',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
